### ISSUE TITLE
✨ NFT_Collection: Section 2 - Get Local Env Running

### ISSUE THREAD

**Issue by adilanchian** [zipeducation/buildspace-projects#102]
### What You Are Changing
Clarifying getting the direct image from imgur

### Anything else?
This is an issue @zzJZzz found, but needs a tad bit more time to get the PR together :)

**Comment by zzJZzz** [comment]
Hey Alec. This is zzJZzz, aka Justin. I just saw your update to my PR.
Clarifying how to get the direct link for imgur.

I did what you suggested and deleted the fork, and started from scratch. I
saw your recent comment. Thank you.

Is there anything else I need to do? Did I provide enough information? Is
it too small of a change?

Thanks again

Initially I sent this by DM. Discord wouldn't let me.

**Comment by adilanchian** [comment]
No worries!

This was perfect 🤘. I have merged it in and added you as a contributor to our project! Thank you for taking the time and making buildspace better <3. 

No contribution is too small here! Always trying to level up. Thanks again!!
