### ISSUE TITLE
✨ Fix typos

### ISSUE THREAD

**Issue by daeshawnballard** [zipeducation/buildspace-projects#14]
### Course Title
*What is the title of the course you are updating?*

The title of the course is Build a Web3 App with Solidity + Ethereum Smart Contracts

### Lesson Title
*What is the title of the lesson you are updating?*

The lesson title is located at Section 2 / Build web3 app that connects to our wallet and talks to our WaveContract / Call the our deployed smart contract from our app

### Why Are You Updating it?
*A short description of the change you made and why!*

" **Call the our** deployed smart contract from our app" should be -> " **Call the** deployed smart contract from our app"
or " **Call our** deployed smart contract from our app"

I am updating it because there is a grammatical error.

**Comment by adilanchian** [comment]
@daeshawnballard - Would you want to submit a PR for it to get some credit?! We would love it :)

**Comment by daeshawnballard** [comment]
> @daeshawnballard - Would you want to submit a PR for it to get some credit?! We would love it :)

I've never done that, but I'd love the opportunity! I also, didn't attempt it because I didn't see the section title in the code, but I'll give it a shot!

**Comment by adilanchian** [comment]
YOU GOT THIS. Checkout our README for some info on getting started :)

Im here to help!!

**Comment by daeshawnballard** [comment]
@adilanchian It looks like this issue's content is inaccessible to me. It is in a header on your website application itself? 
However, I submitted another pull request for issue #45.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/13078855/134993804-7e8c38e2-abb0-4e6b-ba86-d32c1e25f08d.png">

**Comment by adilanchian** [comment]
Oh nice!! yes this is actually generate server side so it would not live in here :).

Going to add this to our backlog to tweak! Thanks for the heads up
