### ISSUE TITLE
Invalid Discord Invite Links

### ISSUE THREAD

**Issue by erhuve** [zipeducation/buildspace-projects#274]
Not sure if this is an issue on my end or actual invalid links.
The discord link in this repo (https://discord.gg/CFuBU7RJ42) is invalid as well as the one on buildspace.so (https://discord.gg/mXDqs6Ubcc).
![image](https://user-images.githubusercontent.com/59463268/139113434-94b109b8-f843-4bac-8197-7485288c5a41.png)

Would love to submit a PR to fix with a permanent invite but it looks like users can't generate invite links.

**Comment by adilanchian** [comment]
Hey @erhuve !

Thanks for the heads up here :). Yes - we recently did a clean up on all our invite links! Where did this invite originate from?

**Comment by erhuve** [comment]
> Hey @erhuve !
> 
> 
> 
> Thanks for the heads up here :). Yes - we recently did a clean up on all our invite links! Where did this invite originate from? 

The first invite is from the readme on this repo, and the second one is from the homepage buildspace.so![image](https://user-images.githubusercontent.com/59463268/139703092-85beec10-0614-4f89-98dc-02dd7f3b9d1c.jpeg)

**Comment by adilanchian** [comment]
OOOO this repo is a good one haha. Thanks so much!!

The one on the homepage should be fixed :). 

I'm going to go ahead and make a quick change for this one here! Salute my friend
