### ISSUE TITLE
✨[Build a web3 app with solidity + ethereum  smart contracts]: <Section_3> - <Storing Messages from users on the blockchain>

### ISSUE THREAD

**Issue by daeshawnballard** [zipeducation/buildspace-projects#45]
### What You Are Changing
Changing the grammar we found to be a little to informal and removing contractions to help a worldwide audience better understand what they are reading.

### Anything else?
*Any other thoughts or concerns? Let us know!*

So, we now have a full-fledged web app that can talk to the blockchain!

Now, if we remember we want our final app to be a place where people can come, wave to us, and send us a message. We also want to show all the past waves/messages we've gotten. That's what we'll be doing in this lesson!

So at the end of the lessons we want to

1. Let users submit a message along with their wave.

2. Have that data saved somehow on the blockchain.

3. Actually show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.

Check out my updated smart contract code. I added lots of comments here to help you see what changed :).

[https://app.buildspace.so/courses/CO02cf0f1c-f996-4f50-9669-cf945ca3fb0b/lessons/LEe9f04c2e-fe9c-4e87-81b2-efb677a1720c](url)

**Comment by adilanchian** [comment]
Heckkkk ya. Thanks for the changes here. Will take a look at the PR and go from there!

**Comment by adilanchian** [comment]
Hey @daeshawnballard do you have a PR open for this?
