### ISSUE TITLE
✨ Lesson Improvement [Build a Web3 App with Solidity + Ethereum Smart Contracts ]: <Section 3> - <Fund contract, set a prize, and send users Ethereum>

### ISSUE THREAD

**Issue by daeshawnballard** [zipeducation/buildspace-projects#49]
### What You Are Changing
*A short description of the change you made and why!*
I am making a grammatical change to this line:

 "Trying to withdraw more money than **they** contract has."
to this 
 "Trying to withdraw more money than **the** contract has."

This fixes a grammatical error and reads better.

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by adilanchian** [comment]
Thanks for the submission! If you made a PR - make sure to tag this issue to it please :)

Will be merging in all the PRs today!

**Comment by adilanchian** [comment]
Merged! Thanks :)
