### ISSUE TITLE
✨ addAccount Balance variable declaration

### ISSUE THREAD

**Issue by brolag** [zipeducation/buildspace-projects#7]
### Course Title
*Build a Web3 App with Solidity + Ethereum Smart Contracts*

### Lesson Title
*Deploy locally so we can start building the website*

### Why Are You Updating it?
*Adding the `accountBalance` variable declaration to avoid issues when running the deploy scriptt*

PR: https://github.com/zipeducation/buildspace-projects/pull/6

**Comment by adilanchian** [comment]
Left a comment for you in PR #6!

Please take a look when you get a moment :)

**Comment by adilanchian** [comment]
LEGEND OUT HERE. Thanks for the contribution again :)
